workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    scripts:
      - name: Build Android APK
        script: |
          gradle wrapper --gradle-version 9.3.1
          ./gradlew assembleDebug
    artifacts:
      - "**/*.apk"
